/**
 * The colour system.
 *
 * Readability pillar: **projectile colour is ownership, always.** Player fire is warm
 * (gold/white), enemy fire is cool (cyan/magenta). Those two families must stay separable in
 * every colourblind mode, which is why the alternate palettes are hand-picked rather than
 * generated by a filter — a naive daltonisation of the default palette collapses the two
 * families together for deuteranopes.
 *
 * Separation is on **luminance and saturation**, not hue alone, so the families remain
 * distinguishable even in full greyscale. Shape reinforces it too: player projectiles render
 * as elongated bolts, enemy projectiles as round orbs.
 */

import * as THREE from 'three';
import { ColorblindMode } from '../core/types';

export interface Palette {
  readonly name: string;

  /** Player weapon fire, indexed by weapon. Bright, warm, high luminance. */
  readonly playerProjectile: readonly number[];
  /** Enemy weapon fire. Cool, mid luminance. */
  readonly enemyProjectile: readonly number[];

  /** Aimed-at-you, dodgeable. */
  readonly telegraphAimed: number;
  /** Lethal if you stand still. The only saturated red in the game. */
  readonly telegraphLethal: number;

  readonly playerHull: number;
  readonly playerAccent: number;
  readonly playerEngine: number;
  readonly playerShield: number;

  readonly enemyHull: number;
  readonly enemyAccent: number;
  readonly enemyEngine: number;
  readonly eliteAura: number;

  readonly bossPhase: readonly number[];

  /** Augment category colours: Offense, Defense, Mobility, Systems. */
  readonly category: readonly number[];
  /** Rarity colours: Common, Rare, Prototype. */
  readonly rarity: readonly number[];

  readonly hudPrimary: number;
  readonly hudDim: number;
  readonly hudWarning: number;
  readonly hudDanger: number;
  readonly hudGood: number;

  readonly arenaBoundary: number;
  readonly nebulaA: number;
  readonly nebulaB: number;
  readonly starTint: number;

  readonly explosionCore: number;
  readonly explosionMid: number;
  readonly explosionSmoke: number;
}

/* Default ------------------------------------------------------------------------------------
 * Player: gold → white-hot. Enemy: cyan → magenta. Maximum hue separation, and the player
 * family also sits ~25% higher in luminance.
 */
const DEFAULT_PALETTE: Palette = {
  name: 'Default',
  playerProjectile: [0xffd166, 0xfff3c4, 0xffc85a, 0xffe08a, 0xffcc70, 0xfff9e6],
  enemyProjectile: [0x1f9fd8, 0xff4fd8, 0x3fc0e8, 0xc44fff],
  telegraphAimed: 0xffd23f,
  telegraphLethal: 0xff2d55,

  playerHull: 0xd8e4f0,
  playerAccent: 0x4fc3f7,
  playerEngine: 0x7ee8ff,
  playerShield: 0x59b6ff,

  enemyHull: 0x3a4258,
  enemyAccent: 0xff4fd8,
  enemyEngine: 0xff5fa8,
  eliteAura: 0xffa63f,

  bossPhase: [0xff4fd8, 0xc44fff, 0xff2d55],

  category: [0xff4d5e, 0x4da6ff, 0x3ddc84, 0xffc23f],
  rarity: [0x9fb3c8, 0x4da6ff, 0xffc23f],

  hudPrimary: 0xbfe9ff,
  hudDim: 0x5f7d94,
  hudWarning: 0xffc23f,
  hudDanger: 0xff2d55,
  hudGood: 0x3ddc84,

  arenaBoundary: 0x2e6f8f,
  nebulaA: 0x1a2a5e,
  nebulaB: 0x4a1f5c,
  starTint: 0xdfe9ff,

  explosionCore: 0xfff6d6,
  explosionMid: 0xff9b3f,
  explosionSmoke: 0x3a3f52,
};

/* Deuteranopia -------------------------------------------------------------------------------
 * Red/green discrimination is lost. Player moves to a high-luminance amber/white; enemies to
 * a saturated blue. Never relies on the red/green axis.
 */
const DEUTERANOPIA_PALETTE: Palette = {
  ...DEFAULT_PALETTE,
  name: 'Deuteranopia',
  playerProjectile: [0xffe066, 0xfffbe0, 0xffc93c, 0xfff0a8, 0xffd24d, 0xfffdf0],
  enemyProjectile: [0x2f9dff, 0x8f6bff, 0x3aa8e8, 0xb08cff],
  telegraphAimed: 0xffe066,
  telegraphLethal: 0x1f4fff,

  playerAccent: 0x66d9ff,
  playerEngine: 0xa8ecff,
  playerShield: 0x4da6ff,
  enemyAccent: 0x8f6bff,
  enemyEngine: 0x9d7bff,
  eliteAura: 0xffd24d,
  bossPhase: [0x2f9dff, 0x8f6bff, 0x1f4fff],

  category: [0xffb020, 0x2f9dff, 0xfff0a8, 0x8f6bff],
  rarity: [0x9fb3c8, 0x2f9dff, 0xffd24d],
  hudWarning: 0xffd24d,
  hudDanger: 0x2f9dff,
  hudGood: 0xfff0a8,
};

/* Protanopia ---------------------------------------------------------------------------------
 * Similar axis loss to deuteranopia but with reds appearing much darker, so we push the
 * player family further toward white and avoid dark reds entirely.
 */
const PROTANOPIA_PALETTE: Palette = {
  ...DEUTERANOPIA_PALETTE,
  name: 'Protanopia',
  playerProjectile: [0xfff0a0, 0xffffff, 0xffe066, 0xfff8d0, 0xffd83c, 0xfffef8],
  enemyProjectile: [0x0090ff, 0x7a5cff, 0x2f9ae0, 0x9f7dff],
  telegraphAimed: 0xfff0a0,
  telegraphLethal: 0x0060ff,
  playerEngine: 0xcaf2ff,
  bossPhase: [0x0090ff, 0x7a5cff, 0x0060ff],
};

/* Tritanopia ---------------------------------------------------------------------------------
 * Blue/yellow discrimination is lost, so the default gold-vs-cyan split fails. Swap to a
 * red/pink player family against a green/teal enemy family.
 */
const TRITANOPIA_PALETTE: Palette = {
  ...DEFAULT_PALETTE,
  name: 'Tritanopia',
  playerProjectile: [0xffc0cd, 0xffe0e6, 0xffcad4, 0xffd6de, 0xffb8c8, 0xfff0f3],
  enemyProjectile: [0x22b899, 0x00b894, 0x35c9a8, 0x0e8f74],
  telegraphAimed: 0xff9db0,
  telegraphLethal: 0xff1f4d,

  playerAccent: 0xffc0cd,
  playerEngine: 0xffe0e6,
  playerShield: 0xffb8c8,
  enemyAccent: 0x22b899,
  enemyEngine: 0x00b894,
  eliteAura: 0xffc0cd,
  bossPhase: [0x22b899, 0x00b894, 0x0e8f74],

  category: [0xff3d63, 0x2fd9b0, 0xffe0e6, 0x00b894],
  rarity: [0x9fb3c8, 0x2fd9b0, 0xff6b8a],
  hudPrimary: 0xffe0e6,
  hudWarning: 0xff9db0,
  hudDanger: 0xff1f4d,
  hudGood: 0x2fd9b0,
};

const PALETTES: readonly Palette[] = [
  DEFAULT_PALETTE,
  DEUTERANOPIA_PALETTE,
  PROTANOPIA_PALETTE,
  TRITANOPIA_PALETTE,
];

let activeMode: ColorblindMode = ColorblindMode.Default;
let active: Palette = DEFAULT_PALETTE;

/** The palette currently in effect. Read it fresh — do not cache across a settings change. */
export function palette(): Palette {
  return active;
}

export function setColorblindMode(mode: ColorblindMode): void {
  activeMode = mode;
  active = PALETTES[mode] ?? DEFAULT_PALETTE;
}

export function getColorblindMode(): ColorblindMode {
  return activeMode;
}

export function paletteName(mode: ColorblindMode): string {
  return (PALETTES[mode] ?? DEFAULT_PALETTE).name;
}

/* Depth cueing ---------------------------------------------------------------------------------
 * A single shared fog colour/density so every system that needs atmospheric depth cueing (the
 * renderer's `scene.fog`, arena dressing shaders that bypass automatic fog) agrees with each
 * other and with the active palette, instead of each guessing its own dim space colour.
 */

/** FogExp2 density. Tuned so combat ranges (well under ARENA.radius) stay essentially unfogged
 * and only distant dressing/backdrop-adjacent geometry genuinely recedes. */
export const DEPTH_FOG_DENSITY = 1 / 1300;

const fogColorScratch = /*#__PURE__*/ new THREE.Color();

/**
 * The ambient depth-fog colour, derived from the active palette's nebula pair so a sector or
 * colourblind-mode change is picked up automatically. Returns a shared scratch instance — copy
 * it into your own uniform/property immediately, never retain the reference.
 */
export function depthFogColor(): THREE.Color {
  const p = active;
  fogColorScratch.copy(color(p.nebulaB)).lerp(color(p.nebulaA), 0.35).multiplyScalar(0.3);
  return fogColorScratch;
}

/* Helpers ------------------------------------------------------------------------------------ */

const colorCache = new Map<number, THREE.Color>();

/**
 * A shared, cached `THREE.Color` for a hex value. Never mutate the result — clone it first.
 * This exists so per-frame code can look up a colour without allocating.
 */
export function color(hex: number): THREE.Color {
  let c = colorCache.get(hex);
  if (!c) {
    c = new THREE.Color(hex);
    colorCache.set(hex, c);
  }
  return c;
}

/** `#rrggbb` string for a hex value, for CSS and DOM UI. */
export function cssColor(hex: number): string {
  return `#${hex.toString(16).padStart(6, '0')}`;
}

/** `rgba(...)` string for a hex value with alpha, for CSS. */
export function cssRgba(hex: number, alpha: number): string {
  const r = (hex >> 16) & 0xff;
  const g = (hex >> 8) & 0xff;
  const b = hex & 0xff;
  return `rgba(${r},${g},${b},${alpha})`;
}

/** Picks a player projectile colour by index, wrapping. */
export function playerProjectileColor(index: number): number {
  const list = active.playerProjectile;
  return list[index % list.length]!;
}

/** Picks an enemy projectile colour by index, wrapping. */
export function enemyProjectileColor(index: number): number {
  const list = active.enemyProjectile;
  return list[index % list.length]!;
}

/**
 * Relative luminance (WCAG), used by the palette self-test to assert that the player and
 * enemy projectile families stay separable even without hue.
 */
export function luminance(hex: number): number {
  const srgb = [((hex >> 16) & 0xff) / 255, ((hex >> 8) & 0xff) / 255, (hex & 0xff) / 255];
  const lin = srgb.map((c) => (c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4)));
  return 0.2126 * lin[0]! + 0.7152 * lin[1]! + 0.0722 * lin[2]!;
}

/**
 * Verifies that in every palette the dimmest player projectile is still meaningfully brighter
 * than the brightest enemy projectile. Called once at boot in dev builds — a failure here
 * means a colourblind player cannot tell incoming fire from their own.
 */
export function verifyPaletteSeparation(): { mode: string; ok: boolean; margin: number }[] {
  return PALETTES.map((p) => {
    let minPlayer = Infinity;
    for (const c of p.playerProjectile) minPlayer = Math.min(minPlayer, luminance(c));
    let maxEnemy = -Infinity;
    for (const c of p.enemyProjectile) maxEnemy = Math.max(maxEnemy, luminance(c));
    const margin = minPlayer - maxEnemy;
    return { mode: p.name, ok: margin > 0.08, margin };
  });
}
